version: '3'

networks:
  sql:

services:
  db:
    container_name: db
    image: postgres:16.0-alpine3.18
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sql

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "80:80"
    env_file:
      - ./.env
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - sql

volumes:
   postgres_volume:
   pgadmin:
